/* Generated By:JJTree: Do not edit this line. /Users/maj/Documents/workspace/sfctest/sfcAST/XmlParserTreeConstants.java */

package sfcAST;

public interface XmlParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSPECIFICATION = 1;
  public int JJTOPT = 2;
  public int JJTDOCTYPE = 3;
  public int JJTVOID = 4;
  public int JJTXMLHEADER = 5;
  public int JJTLIST = 6;
  public int JJTATTRVALUE = 7;
  public int JJTENCODING = 8;
  public int JJTVERSION = 9;
  public int JJTXSINONAMESPACESCHEMALOCATION = 10;
  public int JJTXMLNSXSI = 11;
  public int JJTINTELEMENT = 12;
  public int JJTFLOATELEMENT = 13;
  public int JJTSTRINGELEMENT = 14;
  public int JJT__DEFAULTELEMENT__ = 15;
  public int JJT__DEFAULTATTRIBUTE__ = 16;
  public int JJT_WIDTH = 17;
  public int JJT_VIEWPOSITIONY = 18;
  public int JJT_VIEWPOSITIONX = 19;
  public int JJT_HEIGHT = 20;
  public int JJT_STROKE = 21;
  public int JJT_MODIFIABLE = 22;
  public int JJT_GCTRANSITION = 23;
  public int JJT_UPDATED = 24;
  public int JJT_VERTICALSCROLLBAR = 25;
  public int JJT_USEICON = 26;
  public int JJT_THREADSPEED = 27;
  public int JJT_SOCKETPORT = 28;
  public int JJT_ENABLED = 29;
  public int JJT_ACTIONTEXT = 30;
  public int JJT_NAME = 31;
  public int JJT_GCLINK = 32;
  public int JJT_HORIZONTALSCROLLBAR = 33;
  public int JJT_SCANCYCLE = 34;
  public int JJT_SAVEVERSION = 35;
  public int JJT_CGURI = 36;
  public int JJT_OWNERCLASS = 37;
  public int JJT_DPWSINTERFACE = 38;
  public int JJT_FILENAME = 39;
  public int JJT_ANALOGIN = 40;
  public int JJT_SOCKETHOST = 41;
  public int JJT_COLOR = 42;
  public int JJT_INITIALVALUE = 43;
  public int JJT_CONSTANT = 44;
  public int JJT_MANADJ = 45;
  public int JJT_TOKENLUMINANCE = 46;
  public int JJT_TOOBJECT = 47;
  public int JJT_MACROSTEP = 48;
  public int JJT_EXCEPTIONTRANSITION = 49;
  public int JJT_SIMULATIONMODE = 50;
  public int JJT_DPWSPORT = 51;
  public int JJT_SCALE = 52;
  public int JJT_ANALOGOUT = 53;
  public int JJT_GCINITIALSTEP = 54;
  public int JJT_EXITSTEP = 55;
  public int JJT_CONDITIONVISIBLE = 56;
  public int JJT_ID = 57;
  public int JJT_REALVARIABLE = 58;
  public int JJT_STRINGVARIABLE = 59;
  public int JJT_CHANNEL = 60;
  public int JJT_Y = 61;
  public int JJT_ENTERSTEP = 62;
  public int JJT_X = 63;
  public int JJT_WORKSPACEOBJECT = 64;
  public int JJT_VALUE = 65;
  public int JJT_GCSTEP = 66;
  public int JJT_CYCLIC = 67;
  public int JJT_PARALLELJOIN = 68;
  public int JJT_DIMTICKS = 69;
  public int JJT_GCDOCUMENT = 70;
  public int JJT_FROMOBJECT = 71;
  public int JJT_EXP = 72;
  public int JJT_PARALLELSPLIT = 73;
  public int JJT_ACTIONBLOCKVISIBLE = 74;


  public String[] jjtNodeName = {
    "Start",
    "Specification",
    "Opt",
    "DocType",
    "void",
    "XmlHeader",
    "List",
    "AttrValue",
    "Encoding",
    "Version",
    "XsiNoNamespaceSchemaLocation",
    "XmlnsXsi",
    "IntElement",
    "FloatElement",
    "StringElement",
    "__DefaultElement__",
    "__DefaultAttribute__",
    "_width",
    "_viewPositionY",
    "_viewPositionX",
    "_height",
    "_Stroke",
    "_modifiable",
    "_GCTransition",
    "_updated",
    "_verticalScrollBar",
    "_useIcon",
    "_threadSpeed",
    "_socketPort",
    "_enabled",
    "_actionText",
    "_name",
    "_GCLink",
    "_horizontalScrollBar",
    "_scanCycle",
    "_saveVersion",
    "_CGURI",
    "_ownerClass",
    "_dpwsInterface",
    "_fileName",
    "_AnalogIn",
    "_socketHost",
    "_color",
    "_initialValue",
    "_constant",
    "_manAdj",
    "_tokenLuminance",
    "_toObject",
    "_MacroStep",
    "_ExceptionTransition",
    "_simulationMode",
    "_dpwsPort",
    "_scale",
    "_AnalogOut",
    "_GCInitialStep",
    "_ExitStep",
    "_conditionVisible",
    "_id",
    "_RealVariable",
    "_StringVariable",
    "_channel",
    "_y",
    "_EnterStep",
    "_x",
    "_WorkspaceObject",
    "_value",
    "_GCStep",
    "_cyclic",
    "_ParallelJoin",
    "_dimTicks",
    "_GCDocument",
    "_fromObject",
    "_exp",
    "_ParallelSplit",
    "_actionBlockVisible",
  };
}
