/* Generated By:JJTree&JavaCC: Do not edit this line. XmlParserConstants.java */
package sfcAST;

public interface XmlParserConstants {

  int EOF = 0;
  int XML = 7;
  int DOCTYPE = 8;
  int PUBLIC = 9;
  int encoding = 10;
  int version = 11;
  int XsiNoNamespaceSchemaLocation = 12;
  int XmlnsXsi = 13;
  int _width = 14;
  int _viewPositionY = 15;
  int _viewPositionX = 16;
  int _height = 17;
  int _Stroke = 18;
  int _modifiable = 19;
  int _GCTransition = 20;
  int _updated = 21;
  int _verticalScrollBar = 22;
  int _useIcon = 23;
  int _threadSpeed = 24;
  int _socketPort = 25;
  int _enabled = 26;
  int _actionText = 27;
  int _name = 28;
  int _GCLink = 29;
  int _horizontalScrollBar = 30;
  int _scanCycle = 31;
  int _saveVersion = 32;
  int _CGURI = 33;
  int _ownerClass = 34;
  int _dpwsInterface = 35;
  int _fileName = 36;
  int _AnalogIn = 37;
  int _socketHost = 38;
  int _color = 39;
  int _initialValue = 40;
  int _constant = 41;
  int _manAdj = 42;
  int _tokenLuminance = 43;
  int _toObject = 44;
  int _MacroStep = 45;
  int _ExceptionTransition = 46;
  int _simulationMode = 47;
  int _dpwsPort = 48;
  int _scale = 49;
  int _AnalogOut = 50;
  int _GCInitialStep = 51;
  int _ExitStep = 52;
  int _conditionVisible = 53;
  int _id = 54;
  int _RealVariable = 55;
  int _StringVariable = 56;
  int _channel = 57;
  int _y = 58;
  int _EnterStep = 59;
  int _x = 60;
  int _WorkspaceObject = 61;
  int _value = 62;
  int _GCStep = 63;
  int _cyclic = 64;
  int _ParallelJoin = 65;
  int _dimTicks = 66;
  int _GCDocument = 67;
  int _fromObject = 68;
  int _exp = 69;
  int _ParallelSplit = 70;
  int _actionBlockVisible = 71;
  int INTEGER_LITERAL = 72;
  int DECIMAL_LITERAL = 73;
  int HEX_LITERAL = 74;
  int OCTAL_LITERAL = 75;
  int FLOAT_LITERAL = 76;
  int EXPONENT = 77;
  int CHARACTER_LITERAL = 78;
  int STRING_LITERAL = 79;
  int IDENTIFIER = 80;
  int LETTER = 81;
  int DIGIT = 82;
  int LBRACE = 83;
  int RBRACE = 84;
  int LBRACKET = 85;
  int RBRACKET = 86;
  int LPAR = 87;
  int RPAR = 88;
  int DOT = 89;
  int SEMICOLON = 90;
  int LTSLASH = 91;
  int LTBANG = 92;
  int LT = 93;
  int LTQ = 94;
  int GT = 95;
  int QGT = 96;
  int ASSIGN = 97;

  int DEFAULT = 0;
  int BOUNDS = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"xml\"",
    "\"DOCTYPE\"",
    "\"PUBLIC\"",
    "\"encoding\"",
    "\"version\"",
    "\"xsi:noNamespaceSchemaLocation\"",
    "\"xmlns:xsi\"",
    "\"width\"",
    "\"viewPositionY\"",
    "\"viewPositionX\"",
    "\"height\"",
    "\"Stroke\"",
    "\"modifiable\"",
    "\"GCTransition\"",
    "\"updated\"",
    "\"verticalScrollBar\"",
    "\"useIcon\"",
    "\"threadSpeed\"",
    "\"socketPort\"",
    "\"enabled\"",
    "\"actionText\"",
    "\"name\"",
    "\"GCLink\"",
    "\"horizontalScrollBar\"",
    "\"scanCycle\"",
    "\"saveVersion\"",
    "\"CGURI\"",
    "\"ownerClass\"",
    "\"dpwsInterface\"",
    "\"fileName\"",
    "\"AnalogIn\"",
    "\"socketHost\"",
    "\"color\"",
    "\"initialValue\"",
    "\"constant\"",
    "\"manAdj\"",
    "\"tokenLuminance\"",
    "\"toObject\"",
    "\"MacroStep\"",
    "\"ExceptionTransition\"",
    "\"simulationMode\"",
    "\"dpwsPort\"",
    "\"scale\"",
    "\"AnalogOut\"",
    "\"GCInitialStep\"",
    "\"ExitStep\"",
    "\"conditionVisible\"",
    "\"id\"",
    "\"RealVariable\"",
    "\"StringVariable\"",
    "\"channel\"",
    "\"y\"",
    "\"EnterStep\"",
    "\"x\"",
    "\"WorkspaceObject\"",
    "\"value\"",
    "\"GCStep\"",
    "\"cyclic\"",
    "\"ParallelJoin\"",
    "\"dimTicks\"",
    "\"GCDocument\"",
    "\"fromObject\"",
    "\"exp\"",
    "\"ParallelSplit\"",
    "\"actionBlockVisible\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\";\"",
    "\"</\"",
    "\"<!\"",
    "\"<\"",
    "\"<?\"",
    "\">\"",
    "\"?>\"",
    "\"=\"",
    "\"/>\"",
  };

}
